package com.samsung.camera.intelligence.guidance;

import android.content.Context;
import android.util.Log;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Loads MasterMatch index data from Android assets.
 *
 * Expected files are generated by scripts/export_mastermatch_android.py:
 *   - embeddings JSON: {"count", "embedding_dim", "embeddings": [[...], ...]}
 *   - records JSON:    {"count", "records": [{...}, ...]}
 */
public final class MasterMatchAssetLoader {

    private static final String TAG = "MasterMatchLoader";
    private static volatile String lastLoadError = "idle";

    private MasterMatchAssetLoader() {}

    public static String getLastLoadError() {
        return lastLoadError;
    }

    /**
     * Check whether a single asset exists.
     */
    public static boolean assetExists(Context context, String assetPath) {
        try (InputStream ignored = context.getAssets().open(assetPath)) {
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Check whether both MasterMatch asset files exist.
     */
    public static boolean assetsExist(Context context, String embeddingsAssetPath, String recordsAssetPath) {
        String embeddingsBinPath = embeddingsAssetPath.replaceFirst("\\.json$", ".bin");
        boolean hasJson = assetExists(context, embeddingsAssetPath);
        boolean hasBin = assetExists(context, embeddingsBinPath);
        boolean hasRecords = assetExists(context, recordsAssetPath);
        return (hasJson || hasBin) && hasRecords;
    }

    /**
     * Load assets and populate the given guide's in-memory index.
     *
     * @return true when loading succeeded and index was set, else false.
     */
    public static boolean loadFromAssets(
            Context context,
            MasterMatchGuide guide,
            String embeddingsAssetPath,
            String recordsAssetPath) {
        // Derive binary path from JSON path (e.g. .json -> .bin)
        String binPath = embeddingsAssetPath.replaceFirst("\\.json$", ".bin");
        return loadFromAssets(context, guide, embeddingsAssetPath, binPath, recordsAssetPath);
    }

    /**
     * Load assets with explicit binary embedding path.
     * Prefers .bin (compact binary) over .json (large text).
     *
     * @return true when loading succeeded and index was set, else false.
     */
    public static boolean loadFromAssets(
            Context context,
            MasterMatchGuide guide,
            String embeddingsJsonPath,
            String embeddingsBinPath,
            String recordsAssetPath) {
        try {
            lastLoadError = "loading";
            if (!assetExists(context, recordsAssetPath)) {
                lastLoadError = "records asset missing";
                Log.w(TAG, "Records asset not found: " + recordsAssetPath);
                return false;
            }

            // Load embeddings: prefer binary, fall back to JSON
            float[][] embeddings = null;
            if (assetExists(context, embeddingsBinPath)) {
                Log.i(TAG, "Loading embeddings from binary: " + embeddingsBinPath);
                embeddings = parseEmbeddingsBin(context, embeddingsBinPath);
            } else if (assetExists(context, embeddingsJsonPath)) {
                Log.i(TAG, "Binary not found, falling back to JSON: " + embeddingsJsonPath);
                String embeddingsJson = readAssetText(context, embeddingsJsonPath);
                embeddings = parseEmbeddings(embeddingsJson);
            } else {
                lastLoadError = "embeddings asset missing";
                Log.w(TAG, "No embeddings asset found (tried .bin and .json)");
                return false;
            }

            String recordsJson = readAssetText(context, recordsAssetPath);
            List<MasterMatchGuide.MasterRecord> records = parseRecords(recordsJson);

            if (embeddings.length != records.size()) {
                lastLoadError = "embedding/record count mismatch: " + embeddings.length + " vs " + records.size();
                Log.e(TAG, "Embedding/record count mismatch: " + embeddings.length + " vs " + records.size());
                return false;
            }

            guide.loadIndex(embeddings, records);
            lastLoadError = "none";
            Log.i(TAG, "MasterMatch index loaded: count=" + records.size()
                    + ", dim=" + (embeddings.length > 0 ? embeddings[0].length : 0));
            return true;
        } catch (Exception e) {
            String message = e.getMessage();
            lastLoadError = e.getClass().getSimpleName() + (message != null && !message.isEmpty() ? ": " + message : "");
            Log.e(TAG, "Failed to load MasterMatch assets", e);
            return false;
        } catch (OutOfMemoryError oom) {
            String message = oom.getMessage();
            lastLoadError = "OutOfMemoryError" + (message != null && !message.isEmpty() ? ": " + message : "");
            Log.e(TAG, "Out of memory loading MasterMatch assets", oom);
            return false;
        }
    }

    private static String readAssetText(Context context, String assetPath) throws Exception {
        InputStream inputStream = context.getAssets().open(assetPath);
        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(inputStream, StandardCharsets.UTF_8))) {
            StringBuilder sb = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                sb.append(line);
            }
            return sb.toString();
        }
    }

    /**
     * Parse embeddings from compact binary format.
     * Format: int32 count, int32 dim (little-endian), then count×dim float32 values.
     */
    private static float[][] parseEmbeddingsBin(Context context, String assetPath) throws Exception {
        try (InputStream is = context.getAssets().open(assetPath)) {
            // Read header: count (4 bytes) + dim (4 bytes)
            byte[] header = new byte[8];
            int read = 0;
            while (read < 8) {
                int n = is.read(header, read, 8 - read);
                if (n < 0) throw new IllegalArgumentException("Truncated binary header");
                read += n;
            }
            ByteBuffer hdr = ByteBuffer.wrap(header).order(ByteOrder.LITTLE_ENDIAN);
            int count = hdr.getInt();
            int dim = hdr.getInt();

            if (count <= 0 || dim <= 0 || count > 100_000 || dim > 10_000) {
                throw new IllegalArgumentException("Invalid header: count=" + count + ", dim=" + dim);
            }

            // Read data: count * dim * 4 bytes
            int dataBytes = count * dim * 4;
            byte[] data = new byte[dataBytes];
            read = 0;
            while (read < dataBytes) {
                int n = is.read(data, read, dataBytes - read);
                if (n < 0) throw new IllegalArgumentException("Truncated binary data at byte " + read);
                read += n;
            }

            ByteBuffer buf = ByteBuffer.wrap(data).order(ByteOrder.LITTLE_ENDIAN);
            float[][] embeddings = new float[count][dim];
            for (int i = 0; i < count; i++) {
                for (int j = 0; j < dim; j++) {
                    embeddings[i][j] = buf.getFloat();
                }
            }

            Log.i(TAG, "Binary embeddings loaded: count=" + count + ", dim=" + dim
                    + ", size=" + (dataBytes + 8) + " bytes");
            return embeddings;
        }
    }

    private static float[][] parseEmbeddings(String jsonText) throws Exception {
        JSONObject root = new JSONObject(jsonText);
        JSONArray rows = root.getJSONArray("embeddings");

        int count = rows.length();
        if (count == 0) return new float[0][0];

        JSONArray first = rows.getJSONArray(0);
        int dim = first.length();

        float[][] embeddings = new float[count][dim];
        for (int i = 0; i < count; i++) {
            JSONArray row = rows.getJSONArray(i);
            if (row.length() != dim) {
                throw new IllegalArgumentException("Inconsistent embedding dimension at row " + i);
            }
            for (int j = 0; j < dim; j++) {
                embeddings[i][j] = (float) row.getDouble(j);
            }
        }
        return embeddings;
    }

    private static List<MasterMatchGuide.MasterRecord> parseRecords(String jsonText) throws Exception {
        JSONObject root = new JSONObject(jsonText);
        int formatVersion = root.optInt("format_version", 1);
        if (formatVersion > 4) {
            android.util.Log.w("MasterMatchAssetLoader",
                    "records.json format_version=" + formatVersion + " newer than known (4); ignoring unknown fields");
        }
        JSONArray records = root.getJSONArray("records");

        List<MasterMatchGuide.MasterRecord> out = new ArrayList<>();
        for (int i = 0; i < records.length(); i++) {
            JSONObject r = records.getJSONObject(i);

            String photoId = r.optString("photo_id", "");
            String title = r.optString("title", "");
            String photographerName = r.optString("photographer_name", "");
            String sceneType = r.optString("scene_type", "unknown");
            List<String> styleTags = toStringList(r.optJSONArray("style_tags"));
            String thumbnailUrl = r.optString("thumbnail_url", "");

            Map<String, Object> exif = new HashMap<>();
            JSONObject exifJson = r.optJSONObject("exif");
            if (exifJson != null) {
                putIfPresent(exif, "iso", exifJson, "iso");
                putIfPresent(exif, "shutter_speed", exifJson, "shutter_speed");
                putIfPresent(exif, "aperture", exifJson, "aperture");
                putIfPresent(exif, "aperture_f", exifJson, "aperture_f");
                putIfPresent(exif, "white_balance_kelvin", exifJson, "white_balance_kelvin");
                putIfPresent(exif, "focal_length_mm", exifJson, "focal_length_mm");
                putIfPresent(exif, "sensor_type", exifJson, "sensor_type");
                // Tone style parameters
                putIfPresent(exif, "tone_contrast", exifJson, "tone_contrast");
                putIfPresent(exif, "tone_highlights", exifJson, "tone_highlights");
                putIfPresent(exif, "tone_shadows", exifJson, "tone_shadows");
                putIfPresent(exif, "tone_saturation", exifJson, "tone_saturation");
                putIfPresent(exif, "tone_highlight_warmth", exifJson, "tone_highlight_warmth");
                putIfPresent(exif, "tone_shadow_tint", exifJson, "tone_shadow_tint");
                // Absolute brightness / key target + 3-zone split-tone (format_version >= 4)
                putIfPresent(exif, "tone_target_brightness", exifJson, "tone_target_brightness");
                putIfPresent(exif, "tone_key_strength", exifJson, "tone_key_strength");
                putIfPresent(exif, "split_shadow_wc", exifJson, "split_shadow_wc");
                putIfPresent(exif, "split_shadow_gm", exifJson, "split_shadow_gm");
                putIfPresent(exif, "split_mid_wc", exifJson, "split_mid_wc");
                putIfPresent(exif, "split_mid_gm", exifJson, "split_mid_gm");
                putIfPresent(exif, "split_high_wc", exifJson, "split_high_wc");
                putIfPresent(exif, "split_high_gm", exifJson, "split_high_gm");
            }

            // Top-level camera identity (format_version >= 3); silently ignored otherwise.
            String cameraMake = r.optString("camera_make", "");
            String cameraModel = r.optString("camera_model", "");
            String cameraBrand = r.optString("camera_brand", "");
            Integer cameraClusterId = r.has("camera_cluster_id") && !r.isNull("camera_cluster_id")
                    ? Integer.valueOf(r.optInt("camera_cluster_id", -1)) : null;

            MasterMatchGuide.MasterRecord record = new MasterMatchGuide.MasterRecord(
                    photoId,
                    title,
                    photographerName,
                    sceneType,
                    styleTags,
                    exif,
                    thumbnailUrl,
                    cameraMake,
                    cameraModel,
                    cameraBrand,
                    cameraClusterId
            );
            out.add(record);
        }

        return out;
    }

    private static List<String> toStringList(JSONArray arr) {
        List<String> out = new ArrayList<>();
        if (arr == null) return out;
        for (int i = 0; i < arr.length(); i++) {
            out.add(arr.optString(i, ""));
        }
        return out;
    }

    private static void putIfPresent(Map<String, Object> map, String key, JSONObject src, String srcKey) {
        Object value = src.opt(srcKey);
        if (value != null && value != JSONObject.NULL) {
            map.put(key, value);
        }
    }
}
