// AUTO-GENERATED by scripts/gen_native_rules.py — DO NOT EDIT BY HAND.
// Source: android/app/src/main/assets/trigger_rules.json
#include "trigger_engine.h"

namespace camera_native {

const std::vector<std::string>& trigger_names() {
    static const std::vector<std::string> kNames = {
        "nd_filter",
        "only_me",
        "miniature",
        "flash",
        "tele_portrait",
        "light_box",
        "uw_selfie",
        "lens_blocked",
        "out_of_focus",
        "business_card",
        "wifi_credential",
    };
    return kNames;
}

const std::vector<Rule>& compiled_rules() {
    static const std::vector<Rule> kRules = []() {
        std::vector<Rule> r;
        r.reserve(11);
        {
            Rule rule;
            rule.name = "nd_filter";
            rule.bias = -2.2f;
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 2.0f;
                term.key = "scene_type";
                term.classId = 24;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.0f;
                term.key = "scene_type";
                term.classId = 20;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.0f;
                term.key = "scene_type";
                term.classId = 21;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.4f;
                term.key = "scene_type";
                term.classId = 23;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.2f;
                term.key = "scene_type";
                term.classId = 17;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 0.9f;
                term.key = "scene_type";
                term.classId = 4;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.0f;
                term.key = "scene_type";
                term.classId = 15;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.3f;
                term.key = "subject";
                term.classId = 19;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.5f;
                term.key = "subject";
                term.classId = 21;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 0.7f;
                term.key = "subject";
                term.classId = 22;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 0.9f;
                term.key = "is_repeating_motion";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 0.8f;
                term.key = "is_repeating_motion_flow";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 1.0f;
                term.key = "flow_magnitude";
                term.classId = -1;
                term.thr = 0.3f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = -3.0f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        {
            Rule rule;
            rule.name = "only_me";
            rule.bias = -2.0f;
            {
                Term term;
                term.type = TERM_RANGE;
                term.weight = 2.2f;
                term.key = "face_count";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.5f;
                term.high = 3.5f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_RANGE;
                term.weight = 1.0f;
                term.key = "subject_count";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.5f;
                term.high = 1.5f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = -1.5f;
                term.key = "face_count";
                term.classId = -1;
                term.thr = 4.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 1.2f;
                term.key = "has_background_people";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.5f;
                term.key = "subject";
                term.classId = 0;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.5f;
                term.key = "scene_type";
                term.classId = 0;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -3.0f;
                term.key = "scene_type";
                term.classId = 1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -3.5f;
                term.key = "scene_type";
                term.classId = 2;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = -1.0f;
                term.key = "is_group_selfie";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 1.0f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GATE;
                term.weight = 0.0f;
                term.key = "has_background_people";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        {
            Rule rule;
            rule.name = "miniature";
            rule.bias = -2.5f;
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 2.0f;
                term.key = "scene_type";
                term.classId = 4;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.5f;
                term.key = "scene_type";
                term.classId = 17;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.0f;
                term.key = "subject";
                term.classId = 11;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 0.5f;
                term.key = "scene_type";
                term.classId = 20;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 0.4f;
                term.key = "scene_type";
                term.classId = 23;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 0.4f;
                term.key = "flow_magnitude";
                term.classId = -1;
                term.thr = 0.15f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = -2.0f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 0.8f;
                term.key = "scene_depth_layers";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        {
            Rule rule;
            rule.name = "flash";
            rule.bias = -2.0f;
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.0f;
                term.key = "lighting";
                term.classId = 0;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 0.8f;
                term.key = "lighting";
                term.classId = 1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.5f;
                term.key = "lighting";
                term.classId = 7;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 1.5f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 0.6f;
                term.key = "face_count";
                term.classId = -1;
                term.thr = 1.0f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_INV;
                term.weight = 2.0f;
                term.key = "brightness_value";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -2.0f;
                term.key = "lighting";
                term.classId = 4;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        {
            Rule rule;
            rule.name = "tele_portrait";
            rule.bias = -2.5f;
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 1.3f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_RANGE;
                term.weight = 2.0f;
                term.key = "face_count";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.5f;
                term.high = 1.5f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 1.8f;
                term.key = "bbox_area";
                term.classId = -1;
                term.thr = 0.28f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 1.0f;
                term.key = "sharpness_quality";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 1.2f;
                term.key = "scene_depth_layers";
                term.classId = -1;
                term.thr = 2.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = -2.5f;
                term.key = "blur_level";
                term.classId = -1;
                term.thr = 0.4f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.5f;
                term.key = "subject";
                term.classId = 2;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.0f;
                term.key = "scene_type";
                term.classId = 0;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = -1.0f;
                term.key = "has_background_people";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = -3.5f;
                term.key = "face_count";
                term.classId = -1;
                term.thr = 1.6f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = -1.5f;
                term.key = "subject_count";
                term.classId = -1;
                term.thr = 1.6f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -2.0f;
                term.key = "subject";
                term.classId = 1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -2.0f;
                term.key = "scene_type";
                term.classId = 1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -2.5f;
                term.key = "scene_type";
                term.classId = 2;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GATE;
                term.weight = 0.0f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GATE;
                term.weight = 0.15f;
                term.key = "bg_sharp_ratio";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 1.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        {
            Rule rule;
            rule.name = "light_box";
            rule.bias = -2.5f;
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.5f;
                term.key = "scene_type";
                term.classId = 7;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.0f;
                term.key = "scene_type";
                term.classId = 6;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 1.5f;
                term.key = "subject";
                term.classId = 14;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 0.8f;
                term.key = "subject";
                term.classId = 7;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 1.0f;
                term.key = "bbox_area";
                term.classId = -1;
                term.thr = 0.3f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 0.6f;
                term.key = "bbox_edge_dist";
                term.classId = -1;
                term.thr = 0.05f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 0.8f;
                term.key = "visual_complexity";
                term.classId = -1;
                term.thr = 0.45f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = -2.0f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        {
            Rule rule;
            rule.name = "uw_selfie";
            rule.bias = -2.5f;
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = 2.5f;
                term.key = "scene_type";
                term.classId = 2;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 2.5f;
                term.key = "is_group_selfie";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 1.2f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_RANGE;
                term.weight = 1.5f;
                term.key = "face_count";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 1.6f;
                term.high = 6.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 0.6f;
                term.key = "bbox_area";
                term.classId = -1;
                term.thr = 0.15f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GATE;
                term.weight = 0.1f;
                term.key = "is_group_selfie";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        {
            Rule rule;
            rule.name = "lens_blocked";
            rule.bias = -1.8f;
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 3.0f;
                term.key = "finger_cover";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 0.05f;
                term.key = "blur_level";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = -1.5f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -1.5f;
                term.key = "scene_type";
                term.classId = 13;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -1.5f;
                term.key = "scene_type";
                term.classId = 15;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -1.5f;
                term.key = "scene_type";
                term.classId = 16;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GATE;
                term.weight = 0.0f;
                term.key = "finger_cover";
                term.classId = -1;
                term.thr = 0.65f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_GATE;
                term.weight = 0.0f;
                term.key = "lens_blocked_corner_prob";
                term.classId = -1;
                term.thr = 0.4f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        {
            Rule rule;
            rule.name = "out_of_focus";
            rule.bias = -2.0f;
            {
                Term term;
                term.type = TERM_GT;
                term.weight = 2.0f;
                term.key = "blur_level";
                term.classId = -1;
                term.thr = 0.4f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_INV;
                term.weight = 1.5f;
                term.key = "sharpness_quality";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_INV;
                term.weight = 1.0f;
                term.key = "sharpness";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_INV;
                term.weight = 0.5f;
                term.key = "overall_quality";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        {
            Rule rule;
            rule.name = "business_card";
            rule.bias = -0.85f;
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 1.0f;
                term.key = "business_card";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 0.2f;
                term.key = "has_text";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = -2.0f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -1.5f;
                term.key = "scene_type";
                term.classId = 0;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -1.5f;
                term.key = "scene_type";
                term.classId = 3;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        {
            Rule rule;
            rule.name = "wifi_credential";
            rule.bias = -0.85f;
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 1.0f;
                term.key = "wifi_credential";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = 0.2f;
                term.key = "has_text";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_PROB;
                term.weight = -2.0f;
                term.key = "has_face";
                term.classId = -1;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            {
                Term term;
                term.type = TERM_EQ;
                term.weight = -1.5f;
                term.key = "scene_type";
                term.classId = 0;
                term.thr = 0.5f;
                term.low = 0.0f;
                term.high = 1.0f;
                term.dflt = 0.0f;
                rule.terms.push_back(term);
            }
            r.push_back(std::move(rule));
        }
        return r;
    }();
    return kRules;
}

const std::vector<ArbGroup>& compiled_arbitration() {
    static const std::vector<ArbGroup> kGroups = []() {
        std::vector<ArbGroup> g;
        {
            ArbGroup grp;
            grp.name = "portrait_family";
            grp.margin = 0.03f;
            grp.members.push_back("only_me");
            grp.members.push_back("tele_portrait");
            grp.members.push_back("uw_selfie");
            g.push_back(std::move(grp));
        }
        {
            ArbGroup grp;
            grp.name = "doc_family";
            grp.margin = 0.02f;
            grp.members.push_back("business_card");
            grp.members.push_back("wifi_credential");
            g.push_back(std::move(grp));
        }
        return g;
    }();
    return kGroups;
}

const HysteresisCfg& compiled_hysteresis() {
    static const HysteresisCfg kCfg = {3, 5, 0.7f};
    return kCfg;
}

}  // namespace camera_native
